config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :blog_items
  mount RailsAdmin::Engine => '/t98pnr66vn', as: 'rails_admin'
  resources :categories do
    resources :products
  end
  resources :products
  resources :carts
  resources :line_items

  get 'main/index'
  get 'main/index'
  get 'thanks/index'
  get 'faq/index'
  get 'contacts/index'

  root 'main#index'

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :line_items, dependent: :destroy
  validates :name,presence: true

  validates :email,email:true #TODO email validation


  validates :phone_number,presence: true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:new, :create]
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
=begin
    if @cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end
=end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        OrderMailer.order_email(@order).deliver_later
        OrderMailer.buyer_email(@order).deliver_later
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to thanks_index_path, notice:
            'Thank you for your order.' }
        format.json { render action: 'show', status: :created,
                             location: @order }
      else

        format.html { render action: 'new' }
        format.json { render json: @order.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :second_name,:email, :phone_number, :comment)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>


  <div class="field">
    <%= f.label :name, 'Имя'%><span style="color: red">*</span><br>
    <%= f.text_field :name, class: 'error', placeholder: 'Иван'%>
  </div>
    <div class="field">
    <%= f.label :second_name, 'Фамилия'%><span style="color: red">*</span><br>
    <%= f.text_field :second_name, class: 'error', placeholder: 'Иванов' %>
  </div>
  <div class="field">
    <%= f.label :email %><span style="color: red">*</span><br>
    <%= f.text_field :email, class: 'error', placeholder: 'example@mail.com' %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><span style="color: red">*</span><br>
    <%= f.text_field :phone_number, class: 'error', placeholder: '89451234567' %>
  </div>
    <div class="field">
    <%= f.label :comment, 'Комментариии к заказу' %><br>
    <%= f.text_area :comment , placeholder: 'Ваши комментарии'%>
  </div>
    <h2 class="head">Содержание заказа</h2>
    <table class="table">
      <tbody><tr>
        <th>Наименование</th>
        <th>Цена</th>
      </tr>
      <%@cart.line_items.each do |line_item|%>
          <tr>
            <td><%=line_item.product.title%></td>
            <td><%=line_item.final_price%></td>
          </tr>
      <%end%>
      </tbody></table>

    <p>Сумма заказа: <%=@cart.total_price%></p>
    <div class="actions">
    <%= f.submit 'Создать заказ', :class => "btn btn-green" %>
  </div>
<% end %>
<script>
  $(document).ready(function(){

    $('input#order_name, input#order_second_name, input#order_email, input#order_phone_number').unbind().blur( function(){

      var id = $(this).attr('id');
      var val = $(this).val();

      switch(id)
      {
        case 'order_name':
          var rv_name = /^[a-zA-Zа-яА-Я]+$/;

          if(val.length > 2 && val != '' && rv_name.test(val))
          {
            $(this).css('border', '2px solid #66cc00');
            $(this).removeClass('error');
          }

          else
          {
            $(this).css('border', '2px solid red');
            $(this).addClass('error');
          }
          break;

        case 'order_second_name':
          var rv_name = /^[a-zA-Zа-яА-Я]+$/;

          if(val.length > 2 && val != '' && rv_name.test(val))
          {
            $(this).css('border', '2px solid #66cc00');
            $(this).removeClass('error');
          }

          else
          {
            $(this).css('border', '2px solid red');
            $(this).addClass('error');
          }
          break;

        case 'order_email':
          var rv_email = /^([a-zA-Z0-9_.-])+@([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/;
          if(val != '' && rv_email.test(val))
          {
            $(this).css('border', '2px solid #66cc00');
            $(this).removeClass('error');
          }
          else
          {
            $(this).css('border', '2px solid red');
            $(this).addClass('error');
          }
          break;

        case 'order_phone_number':
          var rv_email = /^([0-9-\s]{11,14})+/;
          if(val != '' && rv_email.test(val))
          {
            $(this).css('border', '2px solid #66cc00');
            $(this).removeClass('error');
          }
          else
          {
            $(this).css('border', '2px solid red');
            $(this).addClass('error');
          }
          break;

      };
    });

    $('form#new_order').submit(function(e) {

      if($('.error').length > 0) {
        return false
      }
      else{
        e.submit();
      }
    });
  });

</script>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.email %></td>
        <td><%= order.phone_number %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="row">
  <div class="content">
    <div class="cart-show">
      <h2 class="head">Оформление заказа</h2>
      <div class="cart-item">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @order.phone_number %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>