config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :blog_items
  mount RailsAdmin::Engine => '/t98pnr66vn', as: 'rails_admin'
  resources :categories do
    resources :products
  end
  resources :products
  resources :carts
  resources :line_items

  get 'main/index'
  get 'main/index'
  get 'thanks/index'
  get 'faq/index'
  get 'contacts/index'

  root 'main#index'

end

app/views/common/_buy.html.erb
<a href="<%=cart_path(@cart.id)%>"> <i class="fa fa-shopping-cart fa-3x"></i><span id="count"><%=@cart.products_quantity%></span></a>

app/views/common/_catalog.html.erb
<div class="menu_bar">
  <div class="vertical_nav">
    <div class="title">
      <h3>Каталог</h3>
    </div>
    <div class="catalog_nav">
      <ul>
          <%@categories.each do |category|%>
              <li ><a <%if @category == category %>class="active"<%end%>href="<%= category_products_path(category) %>"><%=category.category_name%></a></li>
          <%end%>
      </ul>
    </div>
  </div>
</div>

app/views/common/_hit_options.html.erb
<%if product.hit%>
  <div class="labelsBlock">
    <div class="label labelTOP" title="Хит продаж">
        Хит продаж
    </div>
  </div>
<%end%>
<%if product.sale%>
  <div class="labelsBlock">
    <div class="label labelTOP" title="Распродажа">
    Хит продаж
    </div>
  </div>
<%end%>
<%if product.novelty%>
  <div class="labelsBlock">
    <div class="label labelTOP" title="Новинка">
        Хит продаж
    </div>
  </div>
<%end%>

app/views/common/_products.html.erb
<div class="catalog">
  <div style="padding-top: 20px; padding-bottom: 10px;">
    <%if @products.size > 1%>
      Сортировать цены: <a href="<%= products_path(:sort => 'up', :category_id => @category.id)%>" style="color: #66cc00">по возрастанию <i class="fa fa-angle-up" aria-hidden="true"></i></a> / <a href="<%= products_path(:sort => 'down',:category_id => @category.id)%>" style="color: #66cc00">по убыванию <i class="fa fa-angle-down" aria-hidden="true"></i></a></div>
    <%end%>
        <%@products.each do |product|%>
        <div class="itemCatalog">
          <%if product.hit%>
              <div class="hits">
                <div class="hits_empty"></div>
                 <span class="hit" style="left:-58px">HIT</span>
              </div>
          <%end%>
          <%if product.sale%>
              <div class="hits" >
                <div class="hits_empty"></div>
                <span class="hit" style="left:-65px">SALE</span>
              </div>
          <%end%>
          <%if product.novelty%>
              <div class="hits">
                <div class="hits_empty"></div>
                <span class="hit" style="left:-63px">NEW</span>
              </div>
          <%end%>
          <div class="description">
            <%=image_tag(image_url(product.image))%>
            <p title="<%=product.title%>"><%=truncate(product.title,:length => 20) %></p>

            <p class="price">
              <span class="rub">
                <%=product.sizes.minimum(:price) || product.price %>
                <i class="fa fa-rub"></i>
              </span></p>

              <%= form_tag(line_items_url(:id => product.id),:method => "post",:onclick =>"javascript:void(null)")do %>

                <!--<a class="modal" href="modal.html" onclick="javascript:void(null)">
                  <div class="plus">Добавить +</div>
                </a>-->
                <%= link_to product_path(product),:class => 'modal', :remote => true do%>
                  <%=content_tag :div,'Добавить +',:class => 'plus'%>
                <%end%>


                <%submit_tag("добавить",:class =>'plus')  %> <!--Убери-->
            <% end %>

            </p>
          </div>
        </div>
    <%end %>
  <%= will_paginate @products %>
</div>

app/views/common/_slider.html.erb
  <div class="row">
    <div class="slider">
      <ul class="slides">
          <li class="slide"><%=image_tag(asset_url('banner3'))%></li>
          <li class="slide"><%=image_tag(image_url('bedroom_collection'))%></li>
          <li class="slide"><%=image_tag(image_url('dizajn-kvartiri'))%></li>
          <li class="slide"><%=image_tag(image_url('gold'))%></li>
          <li class="slide"><%=image_tag(image_url('sl-1'))%></li>
      </ul>
    </div>
  </div>