config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :blog_items
  mount RailsAdmin::Engine => '/t98pnr66vn', as: 'rails_admin'
  resources :categories do
    resources :products
  end
  resources :products
  resources :carts
  resources :line_items

  get 'main/index'
  get 'main/index'
  get 'thanks/index'
  get 'faq/index'
  get 'contacts/index'

  root 'main#index'

end

app/views/layouts/_buy.html.erb
<a href="<%=cart_path(@cart.id)%>"> <%=fa_icon('shopping-cart 4x')%><%=@cart.products_quantity%></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.9, user-scalable=no">
  <meta name="keywords" content="">
  <meta name="description" content="">
  <% if content_for?(:head) %>
      <%= yield(:head) %>
  <% end %>
  <%= favicon_link_tag %>
  <title><%= (yield :title).presence || 'Svoyadoska' %></title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <div class="header">
      <div class="wrapper_h">
        <div class="logo"><%= link_to image_tag(image_url('logo.png')), root_path %></div>
        <div class="contacts">
          <span>Связь с нами :</span><br>
          <a href="tel:+7-964-570-85-98">+7-964-570-85-98</a>
        </div>
        <div class="delivery"><i class="fa fa-truck" aria-hidden="true"></i> Доставка по Москве и МO</div>
        <div class="buy">
          <%= render('common/buy') %>
        </div>
        <div class="horizontal_nav">
          <ul>
            <li><a href="<%=main_index_path%>">Главная</a></li>
            <li><a href="<%=category_products_path(Category.new.first_category.id)%>">Каталог</a></li>
            <li><a href="<%=contacts_index_path%>">Контакты</a></li>
            <li><a href="<%=faq_index_path%>">FAQ</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%=yield%>
  <div class="row">
    <div class="footer">
        <span class="copyright">
        Copyright © 2015. svoyadoska.ru All rights reserved
        Developed by rodosabc</span>
    </div>
  </div>
</body>
</html>